package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.remoteParameters.hashiCorpVaultParameter
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'MSBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("MSBuild")) {
    params {
        add {
            hashiCorpVaultParameter {
                name = "docker_password"
                query = "password_storage_v2/data/docker!/password"
            }
        }
    }
}
