package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.HashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.hashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<HashiCorpVaultConnection> {
            hashiCorpVaultConnection {
                id = "PROJECT_EXT_4"
                name = "HashiCorp Vault (Sub)"
                vaultId = ""
                url = "https://localhost:8200"
                authMethod = appRole {
                    roleId = "a"
                    secretId = "credentialsJSON:f09b01b5-dfc8-4183-9d53-eb3135fedee1"
                }
            }
        }
        feature1.apply {
        }
    }
}
